### ISSUE TITLE
WSL Support

### ISSUE THREAD

**Issue by giovannicandido** [fmotalleb/nu_plugin_desktop_notifications#2]
Hi the compilation works in wsl on windows but has no effect.
Can we have this support, or could you point me some direction to get this working?

**Comment by fmotalleb** [comment]
well, invoking notify command using **nu.exe** works `(yes using wsl terminal)`
e.g. `nu.exe -c "notify -t sample"`
but I don't know if it is possible to make it work natively inside any wsl terminal. currently, I have some issues with my scheduling, I'll check it as soon as I can
