### ISSUE TITLE
Plugin update on crates.io

### ISSUE THREAD

**Issue by rayanamal** [fmotalleb/nu_plugin_desktop_notifications#7]
Hi there Motalleb.
I'm writing a script that depends on this plugin and my installation method is through cargo. I can't distribute a binary to my users for reasons. In crates.io the latest version of the plugin is for nushell version 0.94. I don't know how cargo stuff works, so if you can push an update to crates.io I'd appreciate it :)

**Comment by fmotalleb** [comment]
Hi, It must be updated now and ill fix the auto-publish action for future

**Comment by rayanamal** [comment]
Thanks!
